import { journalMarkdown, dailyMarkdown } from './generated-content';
export type Category = '博客' | 'Java' | 'AI';
export interface ArticleSource {
  id?: string;
  type: string;
  title: string;
  desc: string;
  category: Category;
  date?: string;
  time: string;
  body: string[];
  publishedAt?: string;
  updatedAt?: string;
  topic?: string | null;
  issue?: string;
  tags?: string[];
}
export interface Article extends ArticleSource {
  id: string;
  publishedAt: string;
  updatedAt: string;
  markdown?: string;
  sections: { id: string; heading: string; text: string }[];
}
export interface DailyIssue {
  date: string;
  title: string;
  headline: string;
  summary: string;
  articleIds: string[];
  supplied?: boolean;
}
const originalArticles: ArticleSource[] = [
  {
    type: '随笔',
    title: '保持好奇，比找到答案更重要',
    desc: '写代码、读书、散步。那些看似无关的事，最终都连接在一起。',
    date: '09.28',
    time: '6 分钟',
    category: '博客',
    body: [
      '刚开始写代码时，我以为成长意味着知道更多答案。后来才发现，更有价值的是不断提出新的问题。',
      '读一本技术之外的书，去一条没有走过的街道，认真听别人讲自己的工作。这些经历并不会立刻变成代码，却会慢慢改变我们理解问题的方式。',
      '这个博客用来记录这些连接：工程实践里的一点发现，读书时的一段思考，还有那些暂时没有答案的问题。保持好奇，也给思考留一点空白。',
    ],
  },
  {
    type: '工程实践',
    title: '从「能用」到「好用」：一次 API 重构',
    desc: '关于边界、命名，以及让下一位维护者少猜一点。',
    date: '09.21',
    time: '8 分钟',
    category: '博客',
    body: [
      '一个好用的 API，应当让调用者知道自己在做什么。重构之前，我先把所有调用场景列出来，再找出真正稳定的边界。',
      '统一错误结构，把隐含约定变成明确的参数，避免让一个方法承担多个意图。这些改变比增加更多抽象更有帮助。',
      '重构之后，我们用原有集成测试验证兼容性，并为失败路径补上检查。清晰的边界让以后修改实现时更有把握。',
    ],
  },
  {
    type: '读书笔记',
    title: '慢下来，才看得见系统的全貌',
    desc: '从《思考，快与慢》聊到软件设计中的直觉与判断。',
    date: '09.14',
    time: '5 分钟',
    category: '博客',
    body: [
      '直觉能帮助我们快速行动，但复杂系统经常要求我们停下来核实。',
      '在设计服务之前，画出数据如何流动，列出失败可能发生在哪里，再检查自己的假设。慢一点不是拖延，而是减少后面的返工。',
    ],
  },
  {
    type: '模型与研究',
    title: '理解多模态：从看见到理解',
    desc: '今天的阅读主题：模型如何连接文字、图像与声音。',
    date: '演示日报',
    time: '4 分钟',
    category: 'AI',
    body: [
      '这是 UI 演示内容，并非今日实时新闻。',
      '本期阅读方向是多模态模型：文字、图像和声音如何被映射到模型可以处理的表示，以及不同输入如何参与推理。',
      '阅读相关研究时，可以关注评测任务、输入限制和失败案例，而不只关注榜单排名。',
    ],
  },
  {
    type: '开发者工具',
    title: '把 AI 放进工作流，而不只是聊天框',
    desc: '从代码审阅到知识检索，寻找真正有用的连接。',
    date: '演示日报',
    time: '5 分钟',
    category: 'AI',
    body: [
      '这是 UI 演示内容，并非今日实时新闻。',
      '尝试 AI 工具时，可以从边界明确、结果容易核验的任务开始，例如生成测试草稿或整理已有文档。',
      '把原始材料、期望结果和验收标准一起提供给工具，并保留人的审阅环节。',
    ],
  },
];

const extraArticles: ArticleSource[] = [
  {
    id: 'error-boundaries',
    category: '博客',
    type: '工程实践',
    title: '把失败路径也当作接口的一部分',
    desc: '超时、重试和错误返回，决定了系统在异常时是否仍然清楚。',
    publishedAt: '2026-09-07',
    time: '阅读笔记',
    body: [
      '设计接口时，成功返回通常最先得到关注。真正影响使用体验的，却常常是请求超时以后会发生什么。',
      '先区分调用方可以修正的输入错误与服务暂时无法处理的问题，再定义清晰的错误结构。重试需要考虑幂等性和退避，否则可能把局部故障放大。',
      '每一种失败都应有可以观察的信号。日志、指标和请求标识一起，才能帮助下一位维护者还原现场。',
    ],
  },
  {
    id: 'reading-source',
    category: '博客',
    type: '工程实践',
    title: '读源码之前，先带上一个问题',
    desc: '从一个具体调用出发，比从第一页读到最后一页更有效。',
    publishedAt: '2026-08-30',
    time: '阅读笔记',
    body: [
      '我读源码的起点通常是一个具体问题：这个对象什么时候创建，这个配置在哪里生效，或者这次调用为什么会阻塞。',
      '沿着调用链建立一张小地图，把核心路径与边界分支分开。先用最小示例验证判断，再补上实现细节。',
      '阅读的产出可以只是一张图和一段说明。能用自己的话解释一个行为，往往比记住更多类名更有价值。',
    ],
  },
  {
    id: 'notes-that-last',
    category: '博客',
    type: '随笔',
    title: '给未来的自己，写一份能读懂的笔记',
    desc: '留下问题、上下文和取舍，而不只是最终答案。',
    publishedAt: '2026-08-23',
    time: '阅读笔记',
    body: [
      '几个月之后，再看当时写下的结论，我常常已经忘记问题为什么出现。于是开始在笔记里多留一段上下文。',
      '记录目标是什么，试过什么，哪些限制影响了选择。这样，笔记就不只是答案仓库，也是判断过程的记录。',
      '写完之后问自己：一个没有参与这件事的人，能否靠这些文字继续工作？这也是检验笔记的好方法。',
    ],
  },
  {
    id: 'walk-and-think',
    category: '博客',
    type: '随笔',
    title: '有些问题，离开屏幕后才想明白',
    desc: '关于散步、停顿，以及给注意力留一点余地。',
    publishedAt: '2026-08-16',
    time: '阅读笔记',
    body: [
      '盯着同一段代码太久，容易把现有实现当成问题本身。离开屏幕一会儿，有时能重新看到真正的目标。',
      '散步没有神奇的效率承诺。它只是让我从细节里退一步，重新排列问题和假设。',
      '回到桌前时，把新的理解先写下来，再决定是否继续改代码。停顿也是工作的一部分。',
    ],
  },
  {
    id: 'book-and-system',
    category: '博客',
    type: '读书笔记',
    title: '从系统思维里，重新理解一个服务',
    desc: '关注反馈、边界和延迟，而不只关注单个组件。',
    publishedAt: '2026-08-09',
    time: '阅读笔记',
    body: [
      '一个服务的表现由很多连接共同决定。数据库响应、调用方重试和资源限制，会通过反馈影响彼此。',
      '在排查问题时，我尝试先画出边界和数据流，再识别哪些反馈可能放大变化。',
      '这份笔记记录一种观察方式：既看局部行为，也看它放进整个系统后的后果。',
    ],
  },
  {
    id: 'ai-evaluation',
    category: 'AI',
    type: '评测与实践',
    title: '评测一个 AI 工具，先定义什么叫做好',
    desc: '从真实任务、失败案例和结果核验开始。',
    publishedAt: '2026-10-01',
    issue: '2026-10-01',
    time: '阅读笔记',
    body: [
      '这是设计示例，不是实时资讯。',
      '评价工具之前，先列出它要完成的任务，以及可以接受的结果。用自己常见的输入建立一组小规模案例。',
      '除了成功率，还应记录失败如何被发现、结果是否能解释，以及审阅需要多少额外工作。',
    ],
  },
];

// Java 核心（领域 01）：从语言基础到 I/O 与新特性的完整正文集合。
// 统一结构：核心结论 → 原理与示例 → 使用边界与踩坑 → 关联问题 → 来源与适用版本。
const javaCoreArticles: ArticleSource[] = [
  {
    id: 'java-first-program',
    category: 'Java',
    topic: 'core',
    type: '语言基础',
    title: '从源码到运行：JDK、JRE 与 JVM 的分工',
    desc: 'javac 编译、字节码与跨平台，一次说清楚。',
    publishedAt: '2026-10-08',
    time: '8 分钟',
    body: [
      'Java 的跨平台能力来自“一次编译，到处运行”：源码先由 javac 编译成与平台无关的字节码（.class），再由各平台上的 JVM 解释或即时编译执行。JDK 是开发工具包（含编译器与调试工具），JRE 是运行时环境，JVM 是其中真正执行字节码的虚拟机。日常开发安装 JDK 即可，它包含 JRE。',
      '一个最小程序从 public class 与 main 方法开始：public static void main(String[] args) 是 JVM 约定的入口。编译 javac Hello.java 生成 Hello.class，运行 java Hello 时类加载器把字节码装入 JVM，校验后开始执行。包名对应目录结构，import 只是编译期的引用简写，不参与打包。',
      '初学者常见的坑：类名必须与 public 类所在文件名一致；环境变量 JAVA_HOME 配错会导致 IDE 与命令行使用不同版本；从 Java 11 起可以用 java Hello.java 直接运行单文件源码，适合写脚本和验证想法，但多文件项目仍应走标准编译流程。',
      '字节码为什么需要校验？JIT 与解释器如何协作？这些问题留到 JVM 领域展开：类加载过程、JIT 编译与分层编译都有独立笔记。',
      '参考 Oracle 官方教程与《Java 核心技术 卷 I》。内容适用于 Java 8 及以上版本，单文件源码运行需要 Java 11+。',
    ],
  },
  {
    id: 'java-data-types',
    category: 'Java',
    topic: 'core',
    type: '语言基础',
    title: '基本数据类型、包装类与自动装箱',
    desc: '八种基本类型、溢出与 Integer 缓存陷阱。',
    publishedAt: '2026-10-08',
    time: '9 分钟',
    body: [
      'Java 有八种基本类型：byte、short、int、long、float、double、char、boolean。基本类型存值、有默认值（字段层面）、不能为 null；对应的包装类是对象，可以放进集合、可以表示 null。选择时默认用基本类型，只有需要 null 语义或泛型参数时才用包装类。',
      '字面量与运算有明确的类型规则：整数字面量默认 int，long 要加 L 后缀；两个 byte 相加结果是 int，需要强转才能赋回 byte。float 和 double 是二进制浮点，0.1 + 0.2 不等于 0.3，金额计算必须用 BigDecimal 或以分为单位的 long。强转大类型到小类型会发生截断，int 溢出会回绕而不报错。',
      '经典陷阱在自动装箱：Integer a = 127, b = 127 时 a == b 为 true，换成 128 就为 false，因为 Integer.valueOf 默认缓存 -128 到 127。包装类比较一律用 equals。另一个坑是拆箱时空指针：Integer 为 null 时赋给 int 直接抛 NullPointerException，接口返回包装类时尤其要防。',
      'String 转数字的 parseInt 与 valueOf 有何区别？switch 为什么能支持 String？字符集与 char 的 UTF-16 编码问题，会在字符串笔记中继续。',
      '依据《Java 语言规范》第 4 章与 Effective Java 第 61 条。缓存上限可通过 -XX:AutoBoxCacheMax 调整（仅限 Integer），描述适用于 Java 8 及以上。',
    ],
  },
  {
    id: 'java-operators-flow',
    category: 'Java',
    topic: 'core',
    type: '语言基础',
    title: '运算符与流程控制：那些容易被忽略的规则',
    desc: '自增、位运算、短路求值与 switch 的演进。',
    publishedAt: '2026-10-08',
    time: '7 分钟',
    body: [
      '这一篇的核心是确定性：Java 的运算符优先级、求值顺序和类型提升规则都是规范写死的，不存在未定义行为。&& 和 || 是短路运算符，左侧能确定结果就不再求右侧，这既是性能特性，也常被用来防空指针。',
      'i++ 与 ++i 的区别在于表达式取旧值还是新值；复合赋值 += 会隐式强转，byte b = 1; b += 1 合法，而 b = b + 1 编译失败。位运算中 >> 带符号右移、>>> 无符号右移，>>> 常用于哈希与编码场景。switch 在 Java 7 开始支持 String，编译期实际转成哈希比较加 equals 确认。',
      '常见坑：忘记 break 导致 switch 贯穿（fall-through），每个 case 结尾都应明确 break 或注释说明有意贯穿；浮点数不要用 == 判等；三目运算符在包装类混合运算时可能触发拆箱空指针。Java 14 起的 switch 表达式（yield、箭头语法）天然没有贯穿问题，新代码建议优先使用。',
      'switch 表达式与模式匹配如何结合？记录模式与密封类在“新特性”笔记中展开。',
      '依据《Java 语言规范》第 15 章，switch 表达式自 Java 14 正式可用。示例适用于 Java 8 及以上，特性标注以 LTS 版本为准。',
    ],
  },
  {
    id: 'java-oop',
    category: 'Java',
    topic: 'core',
    type: '面向对象',
    title: '封装、继承与多态：面向对象的三个支点',
    desc: '不是背定义，而是理解它们各自约束什么。',
    publishedAt: '2026-10-09',
    time: '9 分钟',
    body: [
      '三个特性各解决一个问题：封装约束“谁能碰我的状态”，继承复用“is-a 的结构”，多态让“同一调用点表现出不同行为”。真正难点不在定义，而在判断什么时候不该用——尤其是继承。',
      '封装用 private 字段加受控访问实现，构造器与方法共同维护对象不变量。多态依赖动态绑定：方法调用在运行时按对象的实际类型分派，字段和静态方法则不参与多态。重载是编译期按参数类型选择，重写是运行期按对象类型选择，这两个机制经常被混为一谈。',
      '实践中继承要守住里氏替换原则：子类必须能替换父类出现在任何地方。组合优先于继承——继承暴露父类实现细节、在类之间建立最强的耦合，跨包继承具体类几乎总是坏味道。不想被继承就 final 或密封类，不想被重写的方法也标 final。',
      'equals 与 instanceof 在多态下有什么约定？模板方法模式为什么偏爱抽象类？分别在 Object 方法与设计原则相关笔记中展开。',
      '参考《Effective Java》第 18、19 条（组合优先、为继承设计或禁止继承）。适用于所有 Java 版本。',
    ],
  },
  {
    id: 'java-abstract-interface',
    category: 'Java',
    topic: 'core',
    type: '面向对象',
    title: '抽象类与接口如何分工',
    desc: '默认方法与静态方法加入后，边界发生了什么变化。',
    publishedAt: '2026-10-09',
    time: '8 分钟',
    tags: ['易混淆'],
    body: [
      '一句话区分：接口定义“能做什么”的契约，抽象类沉淀“是什么”的公共实现。一个类可以实现多个接口，但只能继承一个抽象类；接口不能持有实例状态（字段默认 public static final），抽象类可以有构造器和普通字段。',
      'Java 8 给接口加入了 default 与 static 方法，让接口可以向前兼容地演进——Collection 增加 stream() 时，所有既有实现类无需改动。默认方法继承冲突时按规则裁决：类优先于接口，更具体的接口优先，仍无法裁决就必须显式重写并可用 Interface.super.method() 指定。',
      '选型经验：需要多继承能力、定义纯契约时用接口；多个实现共享状态或模板流程时用抽象类（模板方法模式）。别把默认方法当成免费的“多继承状态”，它没有状态，只有行为。还有一个细节：接口方法默认 public，重写时不能收窄访问权限。',
      '函数式接口与 @FunctionalInterface 是什么关系？接口默认方法与 Lambda 如何配合？见 Lambda 与函数式接口笔记。',
      '依据《Java 语言规范》第 9 章与《Effective Java》第 20-22 条。默认方法需要 Java 8+，私有接口方法需要 Java 9+。',
    ],
  },
  {
    id: 'java-object-methods',
    category: 'Java',
    topic: 'core',
    type: '面向对象',
    title: 'equals、hashCode 与 toString 的约定',
    desc: '重写 equals 就必须重写 hashCode，为什么。',
    publishedAt: '2026-10-10',
    time: '9 分钟',
    tags: ['易混淆'],
    body: [
      '核心规则：重写 equals 时必须同时重写 hashCode，且两个 equals 相等的对象必须有相同的哈希值。违反它，对象放进基于哈希的集合（HashMap、HashSet）后会出现“明明存在却找不到”的诡异行为。',
      'equals 的规范约定有五条：自反、对称、传递、一致、对 null 返回 false。实现时先用 == 检查同一引用，再用 instanceof 判断类型并转换，最后逐字段比较；float/double 用 Float.compare/Double.compare，数组字段用 Arrays.equals。hashCode 用 Objects.hash 组合关键字段即可。注意 equals 的参数类型必须是 Object，否则写成重载而非重写，@Override 注解能帮你抓住这个错误。',
      '常见坑：重写 equals 后忘了 hashCode；在哈希集合里修改了参与哈希计算的字段，导致元素“丢失”；equals 依赖可变字段造成行为随时间变化。 compareTo 与 equals 也建议保持一致，否则放进 TreeSet 的去重逻辑会与直觉不符。',
      '哈希定位与冲突如何处理？见集合领域的哈希表实现笔记。== 与 equals 在字符串上还有哪些坑？见字符串常量池笔记。',
      '依据《Effective Java》第 10-12 条与 java.lang.Object 官方文档。Lombok 的 @EqualsAndHashCode 可生成实现，但继承体系下需谨慎使用。',
    ],
  },
  {
    id: 'java-string',
    category: 'Java',
    topic: 'core',
    type: '语言基础',
    title: 'String、字符串常量池与 StringBuilder',
    desc: '不可变性带来的安全、缓存与那些 == 陷阱。',
    publishedAt: '2026-10-10',
    time: '9 分钟',
    tags: ['易混淆'],
    body: [
      'String 是不可变对象：一旦创建内容不会改变，所有“修改”方法都返回新对象。不可变带来线程安全、可缓存哈希值、可安全地作为 Map 键，也让常量池成为可能。频繁拼接要用 StringBuilder（非线程安全、快），多线程共享场景才考虑 StringBuffer。',
      '字面量会进入字符串常量池：String a = "hello"; String b = "hello"; 指向同一对象，a == b 为 true；而 new String("hello") 强制在堆上新建对象，== 为 false。intern() 会把字符串放入常量池并返回池内引用。编译期能对常量表达式做折叠，"a" + "b" 在编译时就变成 "ab"，但变量拼接运行期才执行、不进池。',
      '面试与代码评审中的高频坑：用 == 比较字符串内容（应一律 equals）；循环里用 + 拼接生成大量中间对象（编译器只在简单场景自动优化）；忽略编码问题——String.getBytes() 不指定字符集时用平台默认编码，跨环境行为不一致，应显式写 StandardCharsets.UTF_8。',
      '常量池在 JDK 7 从永久代移到堆中，这对 intern 的语义有什么影响？String 在 Java 9 改为 byte[] 存储（Compact Strings）带来什么收益？这些延伸问题见 JVM 内存与新特性笔记。',
      '依据《Java 语言规范》第 3.10.5 节与 JDK 源码。常量池位置变化以 JDK 7 为界，Compact Strings 自 Java 9 生效。',
    ],
  },
  {
    id: 'java-inner-enum',
    category: 'Java',
    topic: 'core',
    type: '面向对象',
    title: '内部类与枚举：小特性，大用途',
    desc: '四种内部类的语义差异，与枚举的正确打开方式。',
    publishedAt: '2026-10-11',
    time: '8 分钟',
    body: [
      '内部类有四种：成员内部类、静态嵌套类、局部内部类、匿名内部类。关键区别在于是否持有外部类引用：成员内部类隐式持有外部 this，静态嵌套类不持有。枚举本质是 final 类加有限个静态实例，构造器私有，天然可比较、可 switch。',
      '静态嵌套类是最常用的“命名空间分组”工具，Builder 模式几乎都以它实现。匿名内部类在 Java 8 之前承担回调职责，现在大多被 Lambda 取代；但匿名类可以有状态、可以实现多方法接口，这是 Lambda 做不到的。枚举可以带字段和方法，把常量与行为绑定，比一堆 public static final int 强得多。',
      '最常见的坑是隐式引用导致内存泄漏：非静态内部类实例被长生命周期对象持有时，外部类实例无法回收——Android 的 Handler 是著名案例，静态嵌套类加弱引用是标准解法。枚举方面：单例用枚举实现可以免疫反射与序列化攻击，这是 Effective Java 推荐的方式。',
      'Lambda 为什么只能用于函数式接口？枚举单例如何防御序列化破坏？分别见函数式编程与序列化笔记。',
      '参考《Effective Java》第 3、34 条与《Java 语言规范》第 8.9 节。适用于所有主流 Java 版本。',
    ],
  },
  {
    id: 'java-exceptions',
    category: 'Java',
    topic: 'core',
    type: '异常处理',
    title: '异常体系：受检与非受检，以及资源关闭',
    desc: 'Throwable 家族、try-with-resources 与异常设计原则。',
    publishedAt: '2026-10-11',
    time: '9 分钟',
    body: [
      'Throwable 分两支：Error 是 JVM 层面的严重问题（如 OutOfMemoryError），应用通常不应捕获；Exception 分支里，受检异常（IOException 等）强制处理，非受检异常（RuntimeException 及其子类）表示编程错误。设计 API 时的经验法则：调用方可以合理恢复的用受检异常，纯属前置条件违反的用非受检异常。',
      'try-with-resources 让实现 AutoCloseable 的资源自动关闭，关闭顺序与声明相反；try 块与 close() 都抛异常时，close 的异常会被压制（suppressed），可通过 getSuppressed() 取回。异常链用 new XxxException("msg", cause) 保留原始原因，切忌吞掉 cause。',
      '实践中的坑：catch 后只打印日志继续执行，把故障隐藏成脏数据；在 finally 里 return，直接吞掉 try 中的异常；用异常做正常流程控制（如用 NumberFormatException 判断数字），既慢又模糊意图。还有性能事实：抛出异常的开销主要在填充栈轨迹，高频路径上值得注意。',
      '受检异常到底是不是设计失误？Optional 与异常如何分工？自定义业务异常该怎么分层？这些在架构领域的错误处理笔记中继续讨论。',
      '参考《Effective Java》第 69-77 条。try-with-resources 需要 Java 7+，对既存代码改造时优先替换手动 finally 关闭。',
    ],
  },
  {
    id: 'java-generics',
    category: 'Java',
    topic: 'core',
    type: '泛型',
    title: '泛型：类型参数、擦除与通配符',
    desc: '编译期的类型约束，运行期的“不存在”。',
    publishedAt: '2026-10-12',
    time: '10 分钟',
    tags: ['重点'],
    body: [
      '泛型把类型变成参数，让类型错误在编译期暴露，而不是运行期的 ClassCastException。类、接口、方法都可以声明类型参数；泛型方法用 <T> 声明在返回类型之前。使用泛型后，编译器在字节码层面插入必要的类型转换，调用方代码里那些强转就消失了。',
      'Java 泛型通过类型擦除实现：编译后泛型信息大部分被移除，List<String> 和 List<Integer> 在运行期是同一个 List.class。由此产生一组限制：不能 new T()、不能创建泛型数组、不能用 instanceof 检查参数化类型、静态成员不能引用类的类型参数。桥接方法是编译器为保持多态在擦除后自动生成的合成方法。',
      '通配符处理“读写”关系：<? extends T> 适合读取（生产者），<? super T> 适合写入（消费者），即 PECS 原则。常见坑：List<? extends Number> 不能 add 任何元素（null 除外），因为编译器无法确定具体类型；试图用 List<Integer> 赋值给 List<Number> 会编译失败——数组协变是历史遗留，泛型选择了不变来保证安全。',
      '擦除让反射拿不到泛型实参，但 Spring 如何解析出 Repository<User> 里的 User？秘诀在签名中的泛型父类信息与 ResolvableType，见反射笔记。',
      '依据《Java 语言规范》第 4.5 节与《Effective Java》第 26-33 条。PECS = Producer Extends Consumer Super。适用于 Java 5 及以上。',
    ],
  },
  {
    id: 'java-annotations',
    category: 'Java',
    topic: 'core',
    type: '注解',
    title: '注解：让元数据参与编译与运行',
    desc: '元注解、生命周期与注解处理器的边界。',
    publishedAt: '2026-10-12',
    time: '8 分钟',
    body: [
      '注解本质是贴在代码元素上的结构化元数据，本身不产生行为，行为由读取它的人决定：编译器、注解处理器（APT）或运行期反射。自定义注解用 @interface 声明，配合元注解 @Retention（保留到源码/类文件/运行期）与 @Target（可贴位置）。',
      '三个使用层面：编译期检查（@Override、@Deprecated）；编译期生成代码（Lombok、MapStruct 通过 APT 在编译时生成类）；运行期读取（Spring 的 @Component、JUnit 的 @Test 通过反射扫描）。@Repeatable 允许同一注解重复出现，@Inherited 只作用于类继承且仅对类注解有效。',
      '常见误区：以为注解自带逻辑，结果写了注解却没有任何处理器去读；在需要代理的框架（如 Spring）里把注解贴在自调用方法上导致不生效——这是代理机制的限制，见 Spring 领域笔记。写注解时给元素提供合理默认值，能显著降低使用成本。',
      '注解在运行期如何被读到？反射的 getAnnotations 与代理如何配合？见反射笔记。Lombok 生成的代码在调试期怎么看？见工程化领域的构建笔记。',
      '依据《Java 语言规范》第 9.6-9.7 节。内容适用于 Java 8 及以上；APT 相关 API 位于 javax.annotation.processing。',
    ],
  },
  {
    id: 'java-reflection',
    category: 'Java',
    topic: 'core',
    type: '反射',
    title: '反射：在运行期操作类型',
    desc: 'Class、Method 与泛型信息的运行时读取。',
    publishedAt: '2026-10-13',
    time: '9 分钟',
    body: [
      '反射让程序在运行期检查类型并操作成员：入口是 Class 对象（Class.forName、obj.getClass()、String.class 三种获取方式），进而拿到 Field、Method、Constructor 并调用。框架的大量能力——依赖注入、序列化、ORM 映射——都建立在反射之上。',
      '典型操作：method.invoke(obj, args) 调用方法，field.setAccessible(true) 突破私有访问（Java 9 模块系统下对 JDK 内部类受限），clazz.getDeclaredConstructor().newInstance() 创建实例。虽然泛型在运行期被擦除，但声明位置的泛型信息保留在签名中：getGenericSuperclass、ParameterizedType 可以解析出父类或字段声明里的类型实参，Gson 的 TypeToken、Spring 的 ResolvableType 都依赖这一点。',
      '反射的代价：性能低于直接调用（JIT 难以内联，现代 JVM 已有一定优化）、绕过编译期类型检查、setAccessible 破坏封装。业务代码里应优先用接口和多态；确实需要动态能力时，缓存反射对象、考虑 MethodHandle（Java 7+，更接近 JVM 原生调用）。',
      'JDK 动态代理为什么只能代理接口？MethodHandle 与反射的性能差异从何而来？分别见动态代理笔记与 JVM 领域的 JIT 笔记。',
      '依据 java.lang.reflect 官方文档与《Java 核心技术 卷 I》第 5 章。模块限制自 Java 9 起，--add-opens 可临时放开。',
    ],
  },
  {
    id: 'java-proxy',
    category: 'Java',
    topic: 'core',
    type: '反射',
    title: '动态代理：JDK 与 CGLIB 的两条路线',
    desc: 'AOP 的底层机制，以及“自调用失效”的根源。',
    publishedAt: '2026-10-13',
    time: '8 分钟',
    body: [
      '动态代理在运行期生成“包装对象”，在方法调用前后织入横切逻辑（日志、事务、权限），是 Spring AOP 的地基。JDK 动态代理基于接口：Proxy.newProxyInstance 生成实现了目标接口的代理类，调用统一进入 InvocationHandler.invoke。CGLIB 基于继承：生成目标类的子类并重写方法，因此能代理没有接口的类，但对 final 类和 final 方法无能为力。',
      'JDK 代理的调用链是“代理对象 → InvocationHandler → 反射调用目标”；CGLIB 用 FastClass 索引方法，避免了反射开销。选择规则（Spring 默认）：目标实现接口时用 JDK 代理，否则用 CGLIB，也可强制 proxyTargetClass。',
      '最高频的坑是“自调用失效”：同类中 this.methodB() 不经过代理对象，织入逻辑（如事务）不会触发。解法是把调用拆到另一个 Bean、注入自身代理或使用 AopContext。另一个坑：CGLIB 代理的类需要可继承的构造器，Java 16+ 对字节码生成的模块限制需要额外 JVM 参数。',
      'Spring 事务如何借助代理实现？声明式事务的传播机制又是什么？见 Spring 与 Web 领域的框架事务笔记。',
      '依据 JDK Proxy 文档与 CGLIB 项目说明。Spring Boot 2.x 起默认使用 CGLIB（proxyTargetClass=true）。',
    ],
  },
  {
    id: 'java-lambda',
    category: 'Java',
    topic: 'core',
    type: '函数式编程',
    title: 'Lambda 表达式与函数式接口',
    desc: '语法糖之下，是 invokedynamic 的机制升级。',
    publishedAt: '2026-10-14',
    time: '9 分钟',
    body: [
      'Lambda 是“只有一个抽象方法的接口”（函数式接口）的简洁实现：(a, b) -> a + b 就是一个 Comparator<Integer>。四大内置函数式接口覆盖多数场景：Function<T,R>（转换）、Consumer<T>（消费）、Supplier<T>（提供）、Predicate<T>（判断）。方法引用 String::length、System.out::println 是更简的形式。',
      'Lambda 不是匿名内部类的语法糖：它底层用 invokedynamic 在运行期动态生成调用点（LambdaMetafactory），不为每个 Lambda 生成单独的 .class 文件，也没有额外的 this 语义——Lambda 里的 this 指向外围实例。这也是它能被 JVM 持续优化的原因。',
      '使用边界：Lambda 捕获的局部变量必须事实上 final（赋值后不再修改），实例字段不受此限；受检异常不能在 Lambda 内直接抛出，需要包装或自定义函数式接口；调试与栈追踪中 Lambda 的可读性较差，复杂逻辑应抽成具名方法。类型推断依赖目标类型，lambda 不赋值给具体接口就无法独立存在。',
      'Stream 的中间操作为什么是惰性的？默认方法如何让 Collection 无缝获得 forEach？见 Stream 与接口演进笔记。',
      '依据《Java 语言规范》第 15.27 节与 LambdaMetafactory 文档。需要 Java 8 及以上。',
    ],
  },
  {
    id: 'java-stream',
    category: 'Java',
    topic: 'core',
    type: '函数式编程',
    title: 'Stream API：声明式地处理集合',
    desc: '惰性求值、短路操作与并行流的适用边界。',
    publishedAt: '2026-10-14',
    time: '10 分钟',
    tags: ['重点'],
    body: [
      'Stream 把集合操作表达为“流水线”：filter、map、sorted 等中间操作是惰性的，只有遇到 collect、forEach、count 这类终端操作才真正执行。声明式写法让“做什么”与“怎么做”分离，可读性通常优于手写循环。',
      '常用组合：filter 过滤、map 映射、flatMap 拍平嵌套、distinct 去重、sorted 排序、limit/skip 分页；终端侧 collect(Collectors.toList())、groupingBy 分组、partitioningBy 分区、reduce 聚合、findFirst 配合 Optional。短路操作（findFirst、anyMatch）命中即停，惰性 + 短路让大集合上的查找不必全量遍历。',
      '踩坑集中区：Stream 一次性消费，终端操作后再用会抛 IllegalStateException；peek 是调试工具不是业务钩子；并行流 parallelStream 共用 ForkJoinPool 公共池，任务含阻塞 IO 时会拖垮同池任务，且对小集合往往更慢——只有 CPU 密集、数据量大、可拆分的场景才值得并行。副作用（在 map 里改外部状态）违背设计初衷，并行时直接出错。',
      'Collectors 的下游收集器如何组合多层分组？Spliterator 如何支撑并行拆分？并行流背后的 ForkJoinPool 见并发编程领域笔记。',
      '依据 java.util.stream 官方文档与《Java 8 实战》。Collectors.toUnmodifiableList 需要 Java 10+，toList() 便捷方法需要 Java 16+。',
    ],
  },
  {
    id: 'java-optional-time',
    category: 'Java',
    topic: 'core',
    type: '函数式编程',
    title: 'Optional 与 java.time：两个现代化的 API',
    desc: '显式表达“可能没有”，告别 Calendar 的历史包袱。',
    publishedAt: '2026-10-15',
    time: '8 分钟',
    body: [
      'Optional 的用途是方法返回值显式表达“可能没有结果”，把判空从口头约定变成类型签名。常用链：ofNullable 包一层，map 转换，filter 过滤，orElse/orElseGet 取默认，orElseThrow 抛业务异常。java.time 则是线程安全、不可变的时间 API：LocalDate、LocalDateTime、ZonedDateTime、Duration、Period，格式化用 DateTimeFormatter（线程安全）。',
      'Optional 正确姿势：orElseGet 传 Supplier 延迟构造默认值（orElse 的参数会立即求值）；配合 Stream 在 Java 9 起可直接 stream()。时间 API 中，Instant 表示时刻（机器视角），LocalDateTime 没有时区信息，跨时区必须用 ZonedDateTime；与旧 API 互操作走 Date.from(instant) 与 date.toInstant()。',
      'Optional 的误用很典型：当作字段类型（不可序列化、违背设计意图）、当作方法参数（调用方被迫包装）、直接 get()（等于回到 NPE 时代）。时间 API 的坑：SimpleDateFormat 非线程安全（老代码重灾区，换 DateTimeFormatter）；Duration 处理秒级以下，日期差要用 Period 或 ChronoUnit.between。',
      '为什么数据库时间建议存 TIMESTAMP 并带时区？LocalDateTime 与 Instant 在持久化时如何映射？见数据库与持久化领域笔记。',
      '依据《Java 8 实战》与 java.time 官方文档（JSR-310，Java 8 引入）。Optional.stream 需要 Java 9+。',
    ],
  },
  {
    id: 'java-collections-overview',
    category: 'Java',
    topic: 'core',
    type: '集合框架',
    title: '集合框架总览与选型',
    desc: 'List、Set、Map、Queue 四条主线，先选型再看实现。',
    publishedAt: '2026-10-15',
    time: '10 分钟',
    tags: ['重点'],
    body: [
      'Java 集合分四条主线：List 有序可重复（ArrayList、LinkedList），Set 去重（HashSet、TreeSet、LinkedHashSet），Map 键值对（HashMap、TreeMap、LinkedHashMap），Queue/Deque 队列（ArrayDeque、PriorityQueue）。选型的第一性问题不是“哪个快”，而是“需要什么语义”：要不要去重、要不要有序、要不要按排序遍历、是不是多线程共享。',
      '经验性决策路径：单线程随机访问为主 → ArrayList；栈/双端队列 → ArrayDeque（官方推荐替代 Stack）；去重无序 → HashSet；去重且按排序 → TreeSet；键值查找 → HashMap；需要遍历顺序等于插入顺序 → LinkedHashMap/LinkedHashSet；优先级出队 → PriorityQueue。并发容器（ConcurrentHashMap、CopyOnWriteArrayList、阻塞队列）属于并发编程领域，见该领域笔记。',
      '常见误用：初始化不给容量导致多次扩容（可预估时用 new HashMap<>(expectedSize / 0.75 + 1) 这类估算）；用 LinkedList 做随机访问（get(i) 是 O(n)）；把 Map 当对象用（字段固定的数据应定义类）；在 foreach 循环里调用 remove 触发 fail-fast——需要 Iterator.remove 或 removeIf。',
      'ArrayList 扩容为什么是 1.5 倍？哈希表如何处理冲突？fail-fast 的 modCount 机制如何工作？后续集合笔记逐一展开。',
      '依据 Java Collections Framework 官方文档与各实现类源码注释。集合工厂方法 List.of/Map.of（不可变）需要 Java 9+。',
    ],
  },
  {
    id: 'java-arraylist-linkedlist',
    category: 'Java',
    topic: 'core',
    type: '集合框架',
    title: 'ArrayList 与 LinkedList：数组与链表的真实差距',
    desc: '随机访问、插入删除与缓存友好性的权衡。',
    publishedAt: '2026-10-16',
    time: '8 分钟',
    body: [
      '结论先行：绝大多数场景选 ArrayList。数组随机访问 O(1)，插入删除涉及 System.arraycopy 整体搬移；LinkedList 是双向链表，定位第 i 个元素要 O(n) 遍历，只有拿到节点位置后的头尾操作才是 O(1)。“插入多用链表”在真实业务里很少成立，因为插入前往往先要定位。',
      'ArrayList 扩容策略是增长到旧容量的 1.5 倍（newCapacity = old + old/2），并复制数组；预分配容量可以避免多次复制。LinkedList 每个元素都是一个 Node 对象（前后指针 + 数据），内存开销大且对象分散，对 CPU 缓存不友好——这是它实际性能经常不如理论分析的原因。',
      '边界与坑：ArrayList 非线程安全，多线程共享需外部同步或用并发容器；subList 返回的是视图，结构性修改会互相影响（见集合陷阱笔记）；LinkedList 的 listIterator 可以在遍历中高效插入删除，这是它为数不多的优势场景。面试回答建议带时间复杂度对比表和缓存局部性这两个角度。',
      'CopyOnWriteArrayList 适合什么场景？迭代器遍历删除为什么必须用 Iterator.remove？分别见并发容器与集合陷阱笔记。',
      '依据 JDK 源码（ArrayList.grow、LinkedList.node）。描述适用于 Java 8 及以上，ArrayList 自 Java 7 起默认懒初始化数组。',
    ],
  },
  {
    id: 'hashmap',
    category: 'Java',
    topic: 'core',
    type: '集合框架',
    title: 'HashMap：散列、树化与扩容',
    desc: '从 HashMap put 的完整流程，理解哈希定位与冲突处理。',
    publishedAt: '2026-10-17',
    time: '12 分钟',
    tags: ['重点'],
    body: [
      '哈希表（Java 8+ 的 HashMap）用“数组 + 链表/红黑树”组织数据：key 的 hashCode 经扰动函数混合高低位，再与数组长度取模定位桶；多个 key 落入同一桶时挂成链表，链表长度到 8 且数组容量不小于 64 时转红黑树，把冲突下的查询从 O(n) 降到 O(log n)。负载因子默认 0.75，超过即扩容为两倍并重新分布节点。',
      'put 的完整流程：计算扰动后的哈希 → 定位桶 → 桶空则直接放入 → 否则遍历比较（先比哈希再 equals）→ 覆盖或追加（尾插）→ 达到树化条件则树化 → 最后检查 size 是否超过阈值触发扩容。扩容时节点按“高位是 0 还是 1”拆成两条链，分别留在原索引和原索引 + 旧容量，避免了全量重哈希。',
      '高频坑：用可变对象做 key 并修改参与哈希的字段，导致存进去取不出；并发下使用 HashMap（JDK 7 的头插法扩容可能成环，JDK 8 改为尾插仍不保证线程安全，并发场景用 ConcurrentHashMap）；初始容量估算不当引发多次扩容。key 为 null 允许且固定放在 0 号桶。',
      '为什么容量总是 2 的幂？（取模变位运算）扰动函数为什么是高 16 位异或低 16 位？并发版的 ConcurrentHashMap 如何保证安全？见并发编程领域的并发容器笔记。',
      '依据 JDK HashMap 源码与《Java 编程思想》容器章节。树化与尾插法自 Java 8 生效；Java 8 之前的头插法细节仅作历史背景了解。',
    ],
  },
  {
    id: 'java-set-treemap',
    category: 'Java',
    topic: 'core',
    type: '集合框架',
    title: 'HashSet 与 TreeMap：去重、保序与排序',
    desc: '哈希去重、插入顺序与红黑树排序，各自由谁支撑。',
    publishedAt: '2026-10-17',
    time: '8 分钟',
    body: [
      '三个常用集合其实都是 Map 的应用：HashSet 内部就是 HashMap（元素作 key，value 是固定占位对象）；LinkedHashMap 在哈希表上叠加双向链表维持插入序或访问序；TreeMap 用红黑树实现 NavigableMap，key 有序，操作 O(log n)。理解了 Map，这组集合的实现就一通百通。',
      'LinkedHashMap 的 accessOrder 模式（构造函数第三个参数传 true）把“最近访问的节点移到链表尾部”，配合重写 removeEldestEntry 就是经典的 LRU 缓存骨架。TreeMap 的排序依赖 Comparable 或构造时传入 Comparator，支持 headMap、tailMap、floorKey 这类区间查询，是排行榜、时间线类需求的现成轮子。',
      '坑点：TreeMap 的去重/比较只认 compareTo 或 Comparator，与 equals 无关——两者不一致时行为会出乎意料（例如 new BigDecimal("1.0") 与 new BigDecimal("1") 在 TreeMap 里是同一个键）；HashSet 不保证遍历顺序，顺序敏感的场景别依赖它；TreeMap 不允许 null 键（JDK 8 起 Comparator 场景也建议避免）。',
      'LRU 在分布式缓存里怎么做？红黑树与 B+ 树的差异为什么让索引选后者？见缓存中间件与数据库领域笔记。',
      '依据 JDK 源码（LinkedHashMap.afterNodeAccess、TreeMap 红黑树旋转）。适用于 Java 8 及以上。',
    ],
  },
  {
    id: 'java-collection-pitfalls',
    category: 'Java',
    topic: 'core',
    type: '集合框架',
    title: '集合使用陷阱：fail-fast、subList 与不可变集合',
    desc: '那些编译通过、运行爆炸的集合操作。',
    publishedAt: '2026-10-18',
    time: '9 分钟',
    tags: ['易混淆'],
    body: [
      'fail-fast 机制：迭代器创建时记录 modCount（结构修改次数），遍历时发现 modCount 变化就抛 ConcurrentModificationException。所以 foreach 中直接 list.remove 必然失败，正确姿势是 Iterator.remove()、removeIf()，或先收集再批量删除。注意 fail-fast 是“尽力检测”，不是线程安全保障。',
      'subList(from, to) 返回的是原列表的视图而非副本：对视图或原列表做结构性修改会互相影响甚至抛异常，做非结构修改（set）则双方可见。Arrays.asList 返回定长列表，add/remove 直接抛 UnsupportedOperationException。需要独立副本时显式 new ArrayList<>(subList)。',
      '不可变集合的三层语义要分清：Collections.unmodifiableList 是只读视图（底层变化仍可见）；List.of（Java 9+）是真不可变且拒绝 null 元素；List.copyOf（Java 10+）做防御性拷贝。返回集合的 API 应返回不可变副本，防止调用方绕过封装修改内部状态——这与“封装”一节的原则一致。',
      '并发修改的正确方案是什么？CopyOnWriteArrayList 为什么写时复制？见并发编程领域的并发容器笔记。',
      '依据 JDK 源码与官方文档（ArrayList.Itr、SubList、ImmutableCollections）。List.of 需要 Java 9+。',
    ],
  },
  {
    id: 'java-io',
    category: 'Java',
    topic: 'core',
    type: 'I/O',
    title: 'Java I/O：字节流、字符流与装饰器模式',
    desc: 'BIO 的模型，与一套经典的组合式 API 设计。',
    publishedAt: '2026-10-19',
    time: '9 分钟',
    body: [
      'Java I/O（java.io）分两大族：字节流 InputStream/OutputStream 处理原始字节（图片、文件拷贝），字符流 Reader/Writer 处理字符文本（内置编码解码）。这套 API 是装饰器模式的教科书案例：new BufferedReader(new InputStreamReader(new FileInputStream(f), UTF_8)) 层层包装，每层只加一个职责——缓冲、编码转换、数据来源。',
      '文件读写现代写法在 java.nio.file：Files.readAllLines、Files.newBufferedReader、Files.copy，配合 Path 替代 File。缓冲的意义是减少系统调用次数，读写大文件务必加缓冲层；字符流必须显式指定字符集，否则吃平台默认编码的亏。资源关闭统一用 try-with-resources。',
      'BIO 的模型是“连接对应线程、读写阻塞”：服务端每接一个连接就占一个线程，连接多了线程爆炸。这决定了 BIO 只适合连接数少且固定的场景。常见坑：flush 遗忘导致缓冲数据没落盘；用 Reader 读二进制文件造成数据损坏；把大文件一次性 readAllBytes 进内存。',
      'Selector 如何让一个线程管理成千上万的连接？零拷贝为什么快？见 NIO 笔记与计算机基础领域的操作系统 I/O 笔记。',
      '依据《Java 核心技术 卷 II》I/O 章节与 java.nio.file 官方文档。Files API 自 Java 7 引入。',
    ],
  },
  {
    id: 'java-nio',
    category: 'Java',
    topic: 'core',
    type: 'I/O',
    title: 'NIO：Buffer、Channel 与 Selector',
    desc: '非阻塞与多路复用，高并发网络编程的地基。',
    publishedAt: '2026-10-19',
    time: '10 分钟',
    body: [
      'NIO（java.nio）三个核心组件：Channel 是双向通道（对比流的单向），Buffer 是数据的容器（读写都经过它），Selector 让单线程监听多个 Channel 的事件（可读、可写、连接就绪）。这套“多路复用”模型让一个线程能管理海量连接，是 Netty、Tomcat NIO 连接器的基础。',
      'Buffer 的状态机是重点：capacity 容量、limit 读写边界、position 当前位置。写入后必须 flip() 切换到读模式（limit 置为 position、position 归零），读完 clear() 或 compact() 复位。Selector 的使用循环：注册 channel 与关注事件 → select() 阻塞等事件 → 遍历 selectedKeys 处理 → 移除已处理 key。',
      '原生 NIO 的坑出了名地多：Selector 空轮询 bug（epoll 的已知问题，Netty 用重建 Selector 规避）；读写事件处理要处理半包/粘包；ByteBuffer 的直接内存（堆外内存）不受堆大小限制但受 MaxDirectMemorySize 约束，泄漏排查困难。这也是生产环境几乎都用 Netty 而非裸 NIO 的原因。',
      'epoll、select、poll 在操作系统层面差在哪？Netty 的 EventLoop 如何封装这套机制？见计算机基础领域笔记与 Netty 入门笔记。',
      '依据《Netty 权威指南》与 JDK NIO 源码。epoll 空轮询问题在不同 JDK 版本有修复演进，描述以长期支持版本为准。',
    ],
  },
  {
    id: 'java-serialization',
    category: 'Java',
    topic: 'core',
    type: 'I/O',
    title: '序列化：原生机制的问题与现代替代',
    desc: 'Serializable 的安全债，与 JSON/Protobuf 的选择。',
    publishedAt: '2026-10-20',
    time: '8 分钟',
    body: [
      '序列化是对象与字节流的互转，用于持久化和网络传输。Java 原生机制要求实现 Serializable（只是个标记接口），靠 ObjectOutputStream/ObjectInputStream 读写；serialVersionUID 用于校验版本兼容性，不显式声明时类结构变化会导致反序列化失败。transient 字段不参与序列化。',
      '原生序列化的问题已成共识：反序列化可执行构造逻辑之外的字节码路径，历史上造成大量远程执行漏洞（Fastjson、 commons-collections 链都与这个生态有关）；格式冗长、性能差、与语言强绑定。Effective Java 的建议是谨慎使用，跨系统传输优先选 JSON（可读、通用）或 Protobuf（紧凑、带 schema、跨语言）。',
      '实践要点：实现 Serializable 的类必须显式声明 private static final long serialVersionUID；枚举单例天然免疫反序列化破坏，普通单例要加 readResolve；敏感字段用 transient 并在反序列化后重建。Redis 缓存对象、RPC 传输都不建议用 JDK 原生序列化，注意框架默认配置（如 Spring Session 的默认序列化器）。',
      'Jackson 的循环引用和多态反序列化怎么处理？Protobuf 的字段编号为什么不能复用？见 Spring 与 Web、缓存与中间件领域的相关笔记。',
      '依据《Effective Java》第 85-90 条与 Java 对象序列化规范。JEP 290（反序列化过滤器）自 Java 9 提供缓解手段。',
    ],
  },
  {
    id: 'java-netty-intro',
    category: 'Java',
    topic: 'core',
    type: 'I/O',
    title: '网络编程与 Netty 初识',
    desc: '从 Socket 到 EventLoop，理解 RPC 框架的底座。',
    publishedAt: '2026-10-20',
    time: '9 分钟',
    body: [
      'Java 网络编程从 Socket/ServerSocket 起步：服务端 accept 阻塞等待连接，读写基于流。这个模型简单直观，但“一连接一线程”撑不起高并发。Netty 把 NIO 封装成事件驱动框架：Boss 线程组接连接，Worker 线程组（EventLoop）处理读写，业务逻辑写成 ChannelHandler 串成 pipeline。',
      'Netty 的核心抽象：EventLoop 是一个绑定单线程的任务循环，Channel 的整个生命周期都由同一个 EventLoop 处理，天然免锁；ByteBuf 比原生 ByteBuffer 易用（读写双指针、池化、引用计数）；ChannelPipeline 让编解码、粘包处理、业务逻辑分层组合。Dubbo、gRPC、Elasticsearch 的传输层都基于 Netty。',
      '入门阶段的坑：ChannelHandler 分为 @Sharable 可共享与必须每次新建两类，带状态的 Handler 标错会串数据；ByteBuf 的引用计数需要释放，否则堆外内存泄漏；业务耗时操作不能跑在 EventLoop 线程上，要丢给业务线程池，否则阻塞所有该线程上的连接。',
      'TCP 粘包半包的根源是什么？Netty 的零拷贝与堆外内存如何配合？见计算机基础领域网络笔记与 NIO 笔记。',
      '依据《Netty 权威指南》与 Netty 官方文档。示例基于 Netty 4.1.x；Netty 5 长期未转正，生产仍以 4.1 为主流。',
    ],
  },
  {
    id: 'java-new-features',
    category: 'Java',
    topic: 'core',
    type: '新特性',
    title: 'Java 8 之后：值得投入的新特性',
    desc: 'record、sealed、模式匹配、文本块与 var 的实际收益。',
    publishedAt: '2026-10-21',
    time: '10 分钟',
    body: [
      'Java 进入半年一发的快速迭代后，真正改变日常编码的特性集中在几个：record（Java 16，一行定义不可变数据载体）、sealed 类（Java 17，限定许可的子类集合）、switch 与 instanceof 的模式匹配（Java 21 成熟，消灭强转样板）、文本块（Java 15，多行字符串）、var（Java 10，局部变量类型推断）。Stream 与 Optional 属于 Java 8，另有专篇。',
      'record User(String name, int age) 自动生成构造器、访问器、equals/hashCode/toString，DTO、值对象、多返回值场景直接受益；它默认 final、字段私有 final，配合 sealed 接口可以精确建模“有限的数据形态”（例如 Result = Success | Failure），再用模式匹配的 switch 做穷尽性检查——这套组合被称为面向数据编程。',
      '采用建议与边界：var 只在类型显而易见时用（var list = new ArrayList<String>() 可以，var result = process() 不可读）；record 不适合需要可变状态或继承的实体（JPA Entity 别用）；文本块里注意缩进剥离规则与转义。团队层面：升级 JDK 前先确认构建工具、框架与字节码工具的版本支持矩阵。',
      '虚拟线程为什么被称作并发模型的转折点？它属于并发编程领域，见虚拟线程笔记。模块化（JPMS）的收益与成本见工程化领域笔记。',
      '依据各 JEP（395/409/441 等）与 OpenJDK 官方文档。版本标注：文本块 15、record 16、sealed 17、模式匹配 switch 正式于 21。当前 LTS 为 17 与 21。',
    ],
  },
];

// 领域 02-10：每个领域两篇正式知识文章，结构与 Java 核心一致。
const javaDomainArticles: ArticleSource[] = [
  // 02 并发编程
  {
    id: 'java-memory-model',
    category: 'Java',
    topic: 'concurrency',
    type: '并发编程',
    title: 'Java 内存模型：可见性、有序性与 happens-before',
    desc: '并发 Bug 不随机，是内存模型规则被违反的必然结果。',
    publishedAt: '2026-10-22',
    time: '11 分钟',
    tags: ['重点'],
    body: [
      'JMM（Java Memory Model）回答一个问题：一个线程的写入，何时对另一个线程可见。由于 CPU 缓存与指令重排序的存在，不加同步的共享变量读写没有任何保证。happens-before 是 JMM 的核心契约：如果 A happens-before B，则 A 的结果对 B 可见，且 A 的执行顺序排在 B 之前。程序次序、锁、volatile、线程 start/join 等规则共同构成这套契约。',
      'volatile 提供两种保证：写 volatile 变量时把工作内存刷回主存、读时强制从主存加载（可见性）；通过内存屏障禁止特定重排序（有序性）。但它不保证复合操作的原子性，count++ 仍需锁或原子类。双重检查锁单例中，实例字段必须声明 volatile，否则“对象引用可见但构造未完成”的重排序会让调用方拿到半成品对象。',
      '实践中的坑：用普通 boolean 标志位做线程间停止信号，循环线程可能永远看不到更新；误以为 += 一条语句就是原子操作；过度依赖“碰巧没出问题”的测试——并发缺陷在低负载下经常潜伏，需要 jcstress 这类工具或足够压测才能暴露。排查并发问题先画 happens-before 边，再怀疑框架。',
      'CAS 与 ABA 问题如何理解？synchronized 的锁升级路径是什么？线程池参数怎么配？见本领域后续笔记。',
      '依据《Java 并发编程实战》与 JLS 第 17 章。VarHandle（Java 9+）提供更细粒度的内存序控制；描述适用于 Java 8 及以上。',
    ],
  },
  {
    id: 'java-thread-pool',
    category: 'Java',
    topic: 'concurrency',
    type: '并发编程',
    title: '线程池：核心参数、队列与拒绝策略',
    desc: '别再 Executors 一把梭，线程池要按业务画像配置。',
    publishedAt: '2026-10-22',
    time: '10 分钟',
    tags: ['重点'],
    body: [
      'ThreadPoolExecutor 的七个参数决定行为：核心线程数、最大线程数、空闲存活时间、工作队列、线程工厂、拒绝策略。提交流程有严格顺序：未满核心线程则新建线程 → 已满则入队 → 队列满则创建至最大线程 → 再满则执行拒绝策略。理解这个顺序，就能解释为什么“最大线程数”在队列无界时永远不生效。',
      '配置从任务画像出发：CPU 密集型任务线程数接近 CPU 核数（N+1），IO 密集型可以显著放大（常见估算 N × (1 + 等待时间/计算时间)）。队列选择影响语义：LinkedBlockingQueue 无界会堆积请求最终 OOM；SynchronousQueue 直接移交，配合有界最大线程数形成“快速失败”；ArrayBlockingQueue 有界排队是最常用的稳妥选择。拒绝策略默认 AbortPolicy 抛异常，CallerRunsPolicy 让提交方自己执行形成背压。',
      '高频事故点：用 Executors.newFixedThreadPool（无界队列）和 newCachedThreadPool（最大线程数无上限）——阿里规约明确禁止，本质是放弃了容量控制；线程池不复用（每次新建）等于退化成直接 new Thread；shutdown 与 shutdownNow 混用导致任务丢失或中断不响应。给线程工厂起有意义的线程名，排查时 jstack 才能看懂。',
      'ForkJoinPool 与 parallelStream 共用什么池？CompletableFuture 的异步编排怎么配线程池？虚拟线程会不会取代线程池？见本领域异步与虚拟线程笔记。',
      '依据 JDK ThreadPoolExecutor 源码与《Java 并发编程实战》第 8 章。阿里巴巴 Java 开发手册的线程池规约值得直接采用。',
    ],
  },
  // 03 JVM
  {
    id: 'jvm-memory-areas',
    category: 'Java',
    topic: 'jvm',
    type: 'JVM',
    title: 'JVM 内存区域：堆、栈与元空间',
    desc: '对象放在哪、栈帧何时销毁，OOM 为什么有好几种。',
    publishedAt: '2026-10-23',
    time: '10 分钟',
    body: [
      'JVM 运行期数据区分线程共享与线程私有：堆与方法区（JDK 8 起落地为元空间）共享，虚拟机栈、本地方法栈、程序计数器线程私有。堆存对象实例，是 GC 的主战场；栈帧随方法调用创建、返回即销毁，保存局部变量与操作数栈；元空间存类元数据，使用本地内存。程序计数器是唯一不会 OOM 的区域。',
      '一次对象创建的旅程：先在 Eden 分配（很多对象经逃逸分析后甚至直接栈上分配），躲过一次次 Minor GC 后晋升老年代；大对象（超过 -XX:PretenureSizeThreshold）直接进老年代。局部变量表中的引用是 GC Roots 的一部分，这解释了“方法没返回，局部变量引用的对象就不会被回收”。',
      '不同区域的 OOM 要会区分：堆溢出（heap space）多为内存泄漏或堆配置过小；元空间溢出（Metaspace）常见于大量动态生成类（代理、热部署）；栈溢出分 StackOverflowError（深度不够，递归失控）与线程创建失败（unable to create native thread，栈占用 × 线程数超出系统内存）。直接内存溢出（Direct buffer memory）常见于 Netty 堆外内存泄漏。',
      'TLAB 如何减少分配竞争？字符串常量池在堆中的位置变化？GC 如何判定对象已死？见 GC 笔记与 Java 核心的字符串笔记。',
      '依据《深入理解 Java 虚拟机》第 2、3 章。元空间替代永久代自 JDK 8 生效；MaxMetaspaceSize 默认不限制，生产建议显式设置。',
    ],
  },
  {
    id: 'jvm-gc',
    category: 'Java',
    topic: 'jvm',
    type: 'JVM',
    title: '垃圾回收：GC Roots、分代收集与 G1',
    desc: '从可达性分析到停顿控制，理解 GC 的设计取舍。',
    publishedAt: '2026-10-23',
    time: '11 分钟',
    body: [
      'GC 的三个基本问题：回收什么、何时回收、怎么回收。“回收什么”靠可达性分析：从 GC Roots（栈中引用、静态字段、JNI 引用等）出发，不可达的对象判定为垃圾——引用计数法因无法解决循环引用而被主流 JVM 放弃。“怎么回收”基于分代假设：绝大多数对象朝生夕灭，所以新生代用复制算法（快、浪费一半空间），老年代用标记-整理。',
      '收集器演进的主线是停顿控制：Serial/Parallel 追求吞吐（后台计算型应用），CMS 首次尝试并发标记（已废弃），G1 把堆划成等大的 Region、按回收收益优先收集（Garbage First），用 -XX:MaxGCPauseMillis 设定期望停顿；ZGC/Shenandoah 把停顿压到亚毫秒级、与堆大小无关，代价是吞吐略降。选型建议：堆小于 4G 且不在意停顿用 Parallel，4-16G 用 G1（JDK 9+ 默认），大堆低延迟用 ZGC（JDK 17+ 生产可用）。',
      '实践要点：看 GC 日志先关注 Full GC 频率与耗时，频繁 Full GC 多为老年代上涨过快（泄漏或晋升过快）；Young GC 耗时突增常因 Survivor 区太小导致对象提前晋升；不要迷信调参，先用 jstat、GC 日志确认瓶颈在内存分配速率还是对象存活率。System.gc() 建议用 -XX:+DisableExplicitGC 屏蔽。',
      'G1 的 Remembered Set 解决什么问题？写屏障在其中扮演什么角色？ZGC 的染色指针原理？这些延伸问题适合在源码级笔记中展开。',
      '依据《深入理解 Java 虚拟机》第 3 章与各收集器 JEP。G1 自 JDK 9 成为默认收集器；ZGC 生产就绪自 JDK 15。',
    ],
  },
  // 04 Spring 与 Web
  {
    id: 'spring-ioc',
    category: 'Java',
    topic: 'spring',
    type: 'Spring 与 Web',
    title: 'IoC 容器与 Bean 生命周期',
    desc: '从 BeanFactory 到三级缓存，理解 Spring 的地基。',
    publishedAt: '2026-10-24',
    time: '11 分钟',
    tags: ['重点'],
    body: [
      'IoC 的本质是把对象的创建与组装权交给容器：业务类只声明依赖（构造器注入为首选），由 Spring 负责实例化、装配、管理生命周期。ApplicationContext 在 BeanFactory 之上扩展了国际化、事件、AOP 集成等企业能力。Bean 生命周期主线：实例化 → 属性填充 → Aware 回调 → BeanPostProcessor 前置 → 初始化（@PostConstruct、InitializingBean、init-method）→ BeanPostProcessor 后置（AOP 代理在此生成）→ 就绪 → 销毁。',
      '循环依赖是经典考点：Spring 用三级缓存解决单例的构造后循环依赖——一级存成品 Bean，二级存早期暴露的半成品，三级存 ObjectFactory（用于在需要时生成早期代理）。构造器注入的循环依赖无法解决（实例化阶段就需要对方），会直接抛 BeanCurrentlyInCreationException，这其实是好事：它在逼迫你重新审视职责划分。',
      '实践要点：字段注入虽然简洁，但隐藏依赖、不便测试、无法用 final，新代码用构造器注入（Lombok @RequiredArgsConstructor）；@Configuration 类的 full 模式（proxyBeanMethods=true）保证 @Bean 方法调用返回同一实例，lite 模式不保证；BeanPostProcessor 是扩展框架的钥匙——@Autowired 处理、AOP、@Transactional 都基于它。',
      '三级缓存为什么需要 ObjectFactory 而不是直接存半成品？@Transactional 的代理在生命周期哪一环生成？见框架事务笔记与动态代理笔记（Java 核心）。',
      '依据 Spring Framework 官方文档 Core 章节与 AbstractAutowireCapableBeanFactory 源码。适用于 Spring 5/6；Spring Boot 3 需要 JDK 17+。',
    ],
  },
  {
    id: 'spring-transaction',
    category: 'Java',
    topic: 'spring',
    type: 'Spring 与 Web',
    title: '声明式事务：传播机制与失效场景',
    desc: '@Transactional 不是注解，是代理。',
    publishedAt: '2026-10-24',
    time: '10 分钟',
    tags: ['易混淆'],
    body: [
      '@Transactional 的能力完全来自 AOP 代理：方法调用经过代理对象时，拦截器负责开启/提交/回滚事务。七种传播机制中最常用三个：REQUIRED（默认，有则加入无则新建）、REQUIRES_NEW（挂起当前事务另起炉灶，用于独立提交如日志落库）、NESTED（在当前事务内设保存点，回滚不影响外层）。',
      '回滚规则：默认只对 RuntimeException 与 Error 回滚，受检异常即使抛出也会提交——需要 rollbackFor = Exception.class 显式声明。隔离级别默认使用数据库自身设置（MySQL 为可重复读），一般不在应用层改动。只读事务 readOnly=true 不只是约束，还能让某些驱动跳过写检查、配合读写分离路由到从库。',
      '失效场景是高频事故区：自调用（this.method() 绕过代理）；方法非 public；异常被 catch 后没再抛出；多数据源下事务管理器名称指定错误；同一事务里调用 REQUIRES_NEW 却忘了它是独立提交（外层回滚不影响内层已提交数据）。排查时先确认拿到的是代理对象，再确认异常类型与传播配置。',
      '事务与分布式锁同时使用时谁先谁后？（锁在事务外，否则锁释放后事务未提交造成并发读到旧值）多数据源下如何用事务同步机制？见数据库与持久化领域的事务笔记。',
      '依据 Spring 官方文档 Transaction Management 章节与 TransactionInterceptor 源码。描述适用于 Spring 5/6 与 Spring Boot 2/3。',
    ],
  },
  // 05 数据库与持久化
  {
    id: 'mysql-index',
    category: 'Java',
    topic: 'database',
    type: '数据库与持久化',
    title: 'MySQL 索引：B+ 树、最左前缀与覆盖索引',
    desc: '索引不是银弹，是有代价的有序结构。',
    publishedAt: '2026-10-25',
    time: '11 分钟',
    tags: ['重点'],
    body: [
      'InnoDB 索引用 B+ 树：非叶子节点只存键值做路由，叶子节点存数据且用双向链表串联，天然支持范围查询；三层 B+ 树即可支撑千万级行。为什么不用二叉树/B 树/哈希：二叉树可能退化、B 树非叶子存数据导致层数变高、哈希不支持范围与排序。聚簇索引叶子节点存整行，二级索引叶子存主键值，查非索引列需要“回表”。',
      '三条黄金法则：最左前缀——联合索引 (a,b,c) 能服务 a、a+b、a+b+c 的查询条件，跳过 a 直接查 b 用不上；覆盖索引——SELECT 的列都在索引里就无需回表，是优化的首选手段；索引选择性——低区分度列（性别、状态标志）单独建索引收益甚微。执行计划用 EXPLAIN 看 type（至少到 range/ref，警惕 ALL）与 key 是否命中。',
      '失效场景清单：对索引列做函数或运算（DATE(create_time) = ...）；隐式类型转换（varchar 列用数字查询）；LIKE 以 % 开头；联合索引范围查询后的列停止匹配；OR 条件一侧无索引。写入代价也真实存在：每个索引都是一棵需要维护的树，写多读少的表要克制索引数量。',
      '索引下推（ICP）做了什么优化？为什么分页深翻页要先查主键再回表？InnoDB 的行锁如何挂在索引上？见事务与锁笔记。',
      '依据《高性能 MySQL》第 5 章与 MySQL 官方文档 InnoDB 章节。描述以 MySQL 5.7/8.0 为准；函数索引在 8.0 可用。',
    ],
  },
  {
    id: 'mysql-mvcc',
    category: 'Java',
    topic: 'database',
    type: '数据库与持久化',
    title: '事务隔离级别与 MVCC',
    desc: '可重复读如何用 undo log 和 ReadView 实现。',
    publishedAt: '2026-10-25',
    time: '11 分钟',
    tags: ['易混淆'],
    body: [
      '并发事务的三类问题：脏读（读到未提交）、不可重复读（同事务内两次读结果不同）、幻读（两次范围查询行数不同）。四个隔离级别逐级解决：读未提交、读已提交、可重复读（MySQL 默认）、串行化。隔离级别越高并发越差，MySQL 的可重复读通过 MVCC + Next-Key Lock 在很大程度上解决了幻读，这是它区别于标准 SQL 的关键。',
      'MVCC 的机制：每行记录隐藏存储事务 ID 与回滚指针，修改产生 undo log 版本链；事务开启一致性读时生成 ReadView（记录当前活跃事务 ID 集合），判断某个版本是否可见的规则是“版本由已提交事务创建、或本事务自己创建”。读已提交与可重复读的差别仅在 ReadView 生成时机：每条语句生成一次 vs 事务首次一致性读时生成一次。',
      '实践要点：快照读（普通 SELECT）走 MVCC 不加锁，当前读（SELECT ... FOR UPDATE、UPDATE、DELETE）加行锁——同一事务内混用两种读，语义容易出乎意料；长事务让 undo 版本链无法清理，膨胀 undo 表空间并拖慢查询，监控里看到几十分钟的大事务要立即处理；可重复读下的唯一键冲突仍会互相阻塞（当前读），死锁分析从加锁顺序入手。',
      'InnoDB 的行锁、间隙锁与 Next-Key Lock 分别锁什么？Spring 事务传播与数据库隔离级别如何映射？见 Spring 领域的框架事务笔记。',
      '依据《高性能 MySQL》与 MySQL 官方文档 InnoDB Transaction Model。描述以 MySQL 5.7/8.0 InnoDB 为准。',
    ],
  },
  // 06 缓存与中间件
  {
    id: 'redis-structures',
    category: 'Java',
    topic: 'middleware',
    type: '缓存与中间件',
    title: 'Redis 数据结构：五种类型之外的真实用法',
    desc: 'String 存缓存之外，ZSet 与 Hash 才是业务利器。',
    publishedAt: '2026-10-26',
    time: '10 分钟',
    body: [
      'Redis 五种基础结构的定位：String 做缓存与计数（INCR 原子）；Hash 存对象字段（部分更新、省内存，小 Hash 底层是 listpack）；List 是双端链表（LPUSH + BRPOP 可做简单队列）；Set 做去重与交并差（共同关注）；ZSet 用跳表实现带分数的排序（排行榜、延迟队列、时间线）。选型先问“我要对它做什么操作”，结构决定可用命令，命令决定复杂度。',
      '进阶结构解决特定问题：HyperLogLog 以约 12KB 固定内存估算 UV（误差 0.81%）；Bitmap 做签到、在线状态这类布尔集合，亿级用户只占百 MB；Stream 是带消费组的持久化消息结构，比 List 队列可靠。BigKey 是通用敌人：大 Value 让网络传输、持久化 fork、删除都变慢，Hash 字段数过万就该拆分。',
      '实践要点：key 设计带业务前缀与分隔（order:2026:12345），并统一过期时间策略避免永驻；批量操作用 pipeline 而不是循环单发；遍历用 SCAN 不用 KEYS（生产事故常客）；删除大 Key 用 UNLINK 异步释放。分布式锁的 SET NX PX + Lua 释放、看门狗续期等细节，Redisson 已封装，不建议手写。',
      '跳表为什么比红黑树更适合 ZSet？Redis 的持久化 RDB/AOF 如何取舍？缓存与数据库的一致性方案有哪些？见缓存问题笔记。',
      '依据《Redis 设计与实现》与 Redis 官方文档。描述以 Redis 6/7 为准；listpack 自 7.0 全面替代 ziplist。',
    ],
  },
  {
    id: 'cache-problems',
    category: 'Java',
    topic: 'middleware',
    type: '缓存与中间件',
    title: '缓存穿透、击穿、雪崩与数据一致性',
    desc: '四个经典问题，四套标准答案，以及它们的代价。',
    publishedAt: '2026-10-26',
    time: '10 分钟',
    tags: ['重点'],
    body: [
      '三个“穿”的区分：穿透是查询不存在的数据（缓存和库都没有），恶意刷接口即此类——解法是缓存空值（短 TTL）或布隆过滤器前置拦截；击穿是热点 Key 在过期瞬间被并发打到数据库——解法是互斥重建（单线程回源，其余等待）或热点数据不过期 + 后台异步刷新；雪崩是大面积 Key 同时失效或 Redis 宕机——解法是 TTL 加随机抖动、多级缓存、熔断降级与集群高可用。',
      '缓存与数据库一致性没有完美方案，只有取舍。最常用的 Cache Aside：读时先查缓存、未命中回源写缓存；写时先更新数据库、再删除缓存（不是更新缓存——更新在并发下更容易产生脏数据，且计算可能浪费）。删除失败用消息队列或订阅 binlog（Canal）做重试补偿。“先删缓存再更新库”在并发下更容易错，不采用。',
      '实践要点：能接受秒级不一致就用 TTL 兜底一切，强一致诉求应重新评估是否该走缓存；布隆过滤器有假阳性（说存在可能不存在）但绝无假阴性，加入新数据要同步添加、不支持删除（计数布隆或定期重建缓解）；互斥重建要防“锁泄漏”，锁必须带过期时间。监控缓存命中率，命中率骤降往往先于事故出现。',
      '多级缓存（本地 Caffeine + Redis）的一致性如何维护？binlog 订阅的延迟与乱序怎么处理？见架构与分布式领域笔记。',
      '依据缓存设计经典文献与《Redis 设计与实现》。布隆过滤器参数可按预期容量与误判率用公式推算。',
    ],
  },
  // 07 计算机基础
  {
    id: 'tcp-fundamentals',
    category: 'Java',
    topic: 'cs-basics',
    type: '计算机基础',
    title: 'TCP：三次握手、四次挥手与可靠传输',
    desc: '不是背图，是理解“为什么必须这样”。',
    publishedAt: '2026-10-27',
    time: '10 分钟',
    body: [
      'TCP 是全双工的可靠字节流。三次握手的本质是双方确认彼此的收发能力并同步初始序列号：两次不够（无法阻止历史失效的连接请求突然到达服务端造成资源浪费），四次没必要。四次挥手多一次是因为被动关闭方收到 FIN 时可能还有数据没发完，ACK 与 FIN 不能合并。TIME_WAIT 等待 2MSL，既保证最后一个 ACK 丢失时能重传，也让旧连接的报文在网络中消亡。',
      '可靠性由一组机制合成：序列号与确认应答（丢包检测）、超时重传、滑动窗口（流量控制，接收方用窗口大小告知缓冲余量）、拥塞控制（慢启动、拥塞避免、快重传/快恢复，发送方根据网络状况自我调节）。粘包的根源是 TCP 没有消息边界——应用层必须自己定长、加分隔符或在协议头里声明长度。',
      '服务端实践：大量 TIME_WAIT 通常说明应用主动短连接关闭过于频繁，优先改长连接/连接池，而不是急着调内核参数；连接队列（backlog）打满会导致客户端握手失败，Nginx/Netty 都有对应配置；抓包分析用 tcpdump + Wireshark，先过滤会话再看重传与零窗口。HTTPS 在 TCP 之上再加 TLS 握手（1.2 需 2-RTT，1.3 降到 1-RTT）。',
      'HTTP/2 的队头阻塞与 HTTP/3 的 QUIC 如何绕过 TCP？Netty 如何处理粘包半包？见 Java 核心的 Netty 笔记与后续 HTTP 笔记。',
      '依据《TCP/IP 详解 卷 1》与 RFC 793/9293。拥塞控制以 CUBIC（Linux 默认）为背景描述。',
    ],
  },
  {
    id: 'os-io-models',
    category: 'Java',
    topic: 'cs-basics',
    type: '计算机基础',
    title: 'I/O 模型与 epoll：高并发的操作系统底座',
    desc: '阻塞、非阻塞、多路复用、异步，以及 select 为什么被淘汰。',
    publishedAt: '2026-10-27',
    time: '10 分钟',
    body: [
      '一次网络读分两阶段：等数据到达内核缓冲区、把数据从内核拷贝到用户空间。五种 I/O 模型的差别在这两个阶段的等待方式：阻塞 I/O 两阶段都等；非阻塞 I/O 第一阶段轮询；I/O 多路复用（select/poll/epoll）用一次系统调用等待多个 fd 的就绪事件；信号驱动 I/O 靠信号通知；异步 I/O（AIO）两阶段都不等，完成时回调。多路复用让一个线程管理海量连接，是 Nginx、Redis、Netty 的共同底座。',
      'epoll 相对 select/poll 的三个改进：fd 集合存内核（epoll_ctl 注册一次，不必每次全量拷贝）；就绪列表驱动（回调机制，不用 O(n) 遍历全部 fd）；支持边缘触发（ET，只在状态变化时通知一次，要求非阻塞 fd 循环读到 EAGAIN）。LT（水平触发）编程更容错，ET 性能上限更高——Nginx 用 ET，Netty 默认也采用 ET。',
      '零拷贝（sendfile、mmap）减少“磁盘→内核→用户→内核→网卡”的中间拷贝与用户态切换，Kafka 拉取消息、Netty 的 FileRegion 都用它。理解这些模型后再看 Java：BIO 对应线程池 + 阻塞，NIO 的 Selector 在 Linux 上就是 epoll 的封装，Netty 进一步封装了事件循环与半包处理。',
      'Java NIO 的 Selector 空轮询 bug 与 epoll 的关系？AIO 为什么在 Linux 上发展不佳（本质仍基于 epoll）？见 Java 核心的 NIO 笔记。',
      '依据《UNIX 网络编程 卷 1》第 6 章与 Linux epoll man page。描述以 Linux 为准；macOS 对应 kqueue，Windows 对应 IOCP（真异步）。',
    ],
  },
  // 08 架构与分布式
  {
    id: 'distributed-idempotency',
    category: 'Java',
    topic: 'architecture',
    type: '架构与分布式',
    title: '幂等性设计：重试之后如何避免重复执行',
    desc: '超时≠失败，所有重试都在赌对方做了幂等。',
    publishedAt: '2026-10-28',
    time: '10 分钟',
    tags: ['重点'],
    body: [
      '分布式系统里，请求超时不代表没执行——可能服务端已处理但响应丢失。调用方重试、MQ 重复投递、用户双击，都要求接口幂等：执行一次与执行多次的业务效果相同。查询天然幂等，删除可以做成幂等，创建与扣减必须显式设计。',
      '主流方案按场景选择：唯一约束兜底（数据库唯一索引，插入冲突即重复，最可靠的最后防线）；Token 机制（下单前先获取令牌，提交时校验并删除，防表单重复提交）；状态机约束（UPDATE ... SET status = ? WHERE id = ? AND status = 预期状态，乐观锁思想，影响行数为 0 即重复或非法流转）；去重表/Redis SETNX 记录请求 ID。MQ 消费端幂等用“业务唯一键 + 消费记录表”，与业务写入放同一本地事务。',
      '实践要点：幂等键必须由业务语义生成（订单号、支付流水号），不要用时间戳或随机 UUID——同一逻辑请求的多次重试必须携带相同幂等键；幂等检查与业务写入要保证原子性，否则并发下双双通过；返回值也要幂等——重复请求应返回首次的结果而不是报错，调用方才能安全重试。',
      '分布式锁与幂等如何配合？两阶段提交与本地消息表各自适合什么场景？见分布式一致性笔记。',
      '依据业界支付与订单系统的通行设计（参考微信支付、支付宝开放平台的幂等规范）。与具体框架版本无关。',
    ],
  },
  {
    id: 'distributed-consistency',
    category: 'Java',
    topic: 'architecture',
    type: '架构与分布式',
    title: 'CAP、最终一致性与补偿设计',
    desc: '放弃强一致不是妥协，是对网络分区的诚实。',
    publishedAt: '2026-10-28',
    time: '10 分钟',
    body: [
      'CAP 的准确表述：网络分区（P）不可避免时，只能在一致性（C）与可用性（A）之间二选一。CP 系统（如 ZooKeeper、etcd）分区期间拒绝写入以保证一致；AP 系统（如 Eureka、Cassandra）接受写入、事后再收敛。互联网业务大多选 AP + 最终一致，因为用户对“暂时看不到最新”的容忍度远高于“不可用”。',
      '跨服务数据一致的工程方案谱系：2PC 强一致但阻塞且协调者是单点，仅适合短事务与传统企业场景；TCC（Try-Confirm-Cancel）把两阶段挪到业务层，灵活但侵入大、要保证空回滚与防悬挂；本地消息表/事务消息（本地事务与消息发送的原子性）是最常用的最终一致方案，配合消费端幂等与对账补偿；Saga 用一系列本地事务加逆向补偿处理长流程（机酒套餐订单是典型）。',
      '实践要点：先问“这个不一致最长能容忍多久”，秒级可用 TTL/定时校准，分钟级用 MQ 重试，小时级必须有对账任务兜底；补偿动作本身也要幂等；给每个跨服务流程设计“查询真实状态”的对账入口（主动查询支付网关而不是只信回调）。监控不一致的存量与时长，比追求零不一致更现实。',
      'Raft/Paxos 如何在 CP 系统内达成一致？Seata 的 AT 模式如何自动生成反向补偿？留待分布式理论与中间件源码笔记展开。',
      '依据《数据密集型应用系统设计》第 9 章与 CAP 定理原始论文。方案选型描述基于当前主流开源生态（RocketMQ 事务消息、Seata 等）。',
    ],
  },
  // 09 工程化与安全
  {
    id: 'maven-dependencies',
    category: 'Java',
    topic: 'engineering',
    type: '工程化',
    title: 'Maven 依赖管理：传递、冲突与收敛',
    desc: 'NoSuchMethodError 十有八九是依赖冲突。',
    publishedAt: '2026-10-29',
    time: '9 分钟',
    body: [
      'Maven 坐标（groupId:artifactId:version）定位构件，依赖默认传递：A 依赖 B、B 依赖 C，则 A 自动获得 C。冲突裁决规则是“路径最近优先，同路径先声明优先”——这个规则只看声明顺序不看版本高低，所以会“编译通过、运行炸掉”。dependencyManagement 只锁定版本不引入依赖，是收敛多模块项目版本的正确位置（Spring Boot 的 parent/BOM 就是大规模应用）。',
      '排障三板斧：mvn dependency:tree -Dverbose 看冲突与被仲裁掉的版本；在 dependencyManagement 中显式锁定期望版本；用 exclusions 排除不需要的传递依赖（日志框架冲突是重灾区：log4j、logback、slf4j 桥接包要只剩一条路径）。scope 的边界要清楚：provided（编译需要、运行由容器提供，如 servlet-api）、test、runtime（编译不需要、运行需要，如 JDBC 驱动）。',
      '实践要点：遇到 NoClassDefFoundError / NoSuchMethodError 先怀疑依赖版本而不是代码；快照版本（SNAPSHOT）只用于内部迭代，发布必须是固定版本；公司内部用私服统一代理与发布；定期检查依赖更新与安全公告。Gradle 的依赖解析默认选最高版本，策略不同，但冲突排查思路相同。',
      'Spring Boot 的 starter 如何利用 BOM 收敛版本？jar 包冲突在容器化部署中有哪些新表现？见 Spring 与部署领域相关笔记。',
      '依据 Maven 官方文档 Dependency Mechanism 章节。描述适用于 Maven 3.x；Gradle 用户可对照其 dependency constraints。',
    ],
  },
  {
    id: 'testing-pyramid',
    category: 'Java',
    topic: 'engineering',
    type: '工程化',
    title: '测试金字塔与可维护的单元测试',
    desc: '测试的价值不在覆盖率数字，在敢不敢重构。',
    publishedAt: '2026-10-29',
    time: '9 分钟',
    body: [
      '测试金字塔的配比逻辑：单元测试数量最多（快、隔离、定位准），集成测试次之（验证组件间协作，如数据库、HTTP 客户端），端到端测试最少（慢、脆、维护贵）。比例失调成“冰淇淋筒”（大量 E2E）的团队，CI 动辄半小时且失败原因难查。单元测试的标准：毫秒级、可重复、不依赖外部服务与执行顺序。',
      'JUnit 5 + Mockito 是 Java 单测的事实标准：@Mock 替代协作对象，when/thenReturn 定义行为，verify 验证交互，@InjectMocks 注入被测对象；断言用 AssertJ 的流式 API 可读性更好。集成测试用 @SpringBootTest 起真实上下文、Testcontainers 起真实数据库（Docker 容器），避免“H2 能过、MySQL 挂掉”的假安全。',
      '实践要点：测试行为不测实现——mock 过多、断言绑死内部调用顺序的测试，重构一次红一片；一个测试只验证一个概念，命名说清场景与期望（should_throw_when_quota_exceeded）；把构建测试数据的成本收进 Builder/工厂方法；TDD 不强求，但“先写失败用例再修 bug”的回归测试必须留下。变异测试（PIT）能发现“断言形同虚设”的用例。',
      'Spring 的 @Transactional 测试回滚机制如何工作？WireMock 与 Mockito 的边界怎么划？见 Spring 领域笔记与后续测试专题。',
      '依据《单元测试的艺术》与 JUnit 5、Testcontainers 官方文档。覆盖率工具 JaCoCo 与 CI 集成的阈值策略按团队约定。',
    ],
  },
  // 10 部署与排障
  {
    id: 'docker-java',
    category: 'Java',
    topic: 'ops',
    type: '部署与排障',
    title: 'Java 应用容器化：镜像、JVM 与资源感知',
    desc: '把 jar 打进镜像只是开始，JVM 要读懂 cgroup。',
    publishedAt: '2026-10-30',
    time: '9 分钟',
    body: [
      'Java 容器化的三个关注点：镜像分层（基础镜像 → 依赖层 → 应用层，变动少的层前置以提高构建缓存命中）、JVM 资源感知、优雅停机。Dockerfile 常见模式是多阶段构建：先用 Maven 镜像构建，再把产物拷进精简的 JRE 运行时镜像（如 eclipse-temurin 的 jre 镜像），镜像体积从 GB 级降到两百 MB 左右。',
      'JVM 与容器的磨合是历史重灾区：JDK 8u191 之前 JVM 读取的是宿主机 CPU/内存而非容器限额，导致堆过大被 OOMKilled 或线程池按宿主机核数膨胀；现代版本（8u191+、11+）默认感知 cgroup，用 -XX:MaxRAMPercentage 控制堆占容器内存的比例——容器里不要再写死 -Xmx，要给元空间、线程栈、堆外内存留余量。CPU 限额会压缩 JIT 编译与 GC 线程的资源，核数估算可显式 -XX:ActiveProcessorCount。',
      '生产要点：容器必须配置优雅停机——K8s 滚动更新先发 SIGTERM，Spring Boot 开启 server.shutdown=graceful 让进行中的请求完成，并确保 preStop 与 terminationGracePeriodSeconds 大于最长请求耗时；健康检查区分 liveness（进程活着）与 readiness（可接流量），探活接口不能依赖慢资源；时区、字符集、临时目录这些“宿主机默认值”在精简镜像里经常缺失，显式配置。',
      'K8s 的 requests/limits 如何影响调度与驱逐？JVM 在容器里如何导出 dump 文件？见线上排障笔记。',
      '依据 Docker 官方文档、JDK 8u191/10 的容器支持改进、Spring Boot graceful shutdown 文档。',
    ],
  },
  {
    id: 'online-troubleshooting',
    category: 'Java',
    topic: 'ops',
    type: '部署与排障',
    title: '线上排障路径：CPU 飙高与内存异常',
    desc: '先稳住现场，再保留证据，最后定位根因。',
    publishedAt: '2026-10-30',
    time: '10 分钟',
    tags: ['重点'],
    body: [
      '排障的第一原则：先恢复、再定位。流量能切走就先切走（摘流、回滚、重启），但动手前尽量保留现场证据——jstack 打线程快照、jmap 或容器内 jcmd 导堆快照、留存 GC 与业务日志。没有证据的重启等于销毁案发现场，同样的问题还会再来。',
      'CPU 飙高的标准路径：top 找到高耗 CPU 的进程 → top -Hp 找到线程 → 线程 PID 转十六进制 → jstack 中查 nid=0x... 的栈。典型根因：死循环/正则回溯、频繁 Young GC（GC 线程吃满 CPU，此时看 GC 日志而不是业务栈）、自旋等待。内存异常路径：OOM 日志或老年代持续上涨 → jmap -histo 看对象分布 → MAT 分析堆快照找支配树与泄漏 suspect。Arthas 把这套流程在线化：watch 观测方法入参返回、trace 看调用耗时、dashboard 总览，无需重启。',
      '实践要点：JVM 参数提前配好 -XX:+HeapDumpOnOutOfMemoryError 与 dump 路径，出事才有快照可分析；线程名要有业务含义（自定义线程工厂），否则 jstack 里全是 pool-1-thread-1；容器环境注意 JDK 工具与目标 JVM 版本匹配，jcmd 是容器内首选；把每次事故写成复盘（现象、时间线、根因、止血、改进项），沉淀在本领域目录下——这比任何工具都更能提升下一次的 MTTR。',
      '频繁 Full GC 如何从 GC 日志读出根因？MAT 的支配树与泄漏报告怎么读？见 JVM 领域的 GC 与诊断笔记。',
      '依据《深入理解 Java 虚拟机》故障处理章节、Arthas 官方文档与一线运维实践。工具描述以 JDK 8+ 附带工具为准。',
    ],
  },
];

const slugs = ['stay-curious', 'api-refactor', 'slow-thinking', 'multimodal', 'ai-workflow'];
const topics = [null, null, null, null, null];
const dates = ['2026-09-28', '2026-09-21', '2026-09-14', '2026-10-03', '2026-10-02'];
const KNOWLEDGE_HEADINGS = ['核心结论', '原理与示例', '使用边界与踩坑', '关联问题', '来源与适用版本'];
export const articles: Article[] = [
  ...originalArticles.map((a, i) => ({
    ...a,
    id: slugs[i],
    topic: topics[i],
    publishedAt: dates[i],
    updatedAt: dates[i],
    issue: i >= 3 ? dates[i] : undefined,
  })),
  ...extraArticles,
  ...javaCoreArticles,
  ...javaDomainArticles,
].map((a) => ({
  ...a,
  id: a.id!,
  publishedAt: a.publishedAt!,
  markdown: journalMarkdown[a.id!],
  updatedAt: a.updatedAt || a.publishedAt!,
  sections: a.body.map((text, i) => ({
    id: `section-${i + 1}`,
    heading:
      (a.category === 'Java' ? KNOWLEDGE_HEADINGS[i] : undefined) ||
      ['问题与背景', '理解与实践', '继续思考'][i] ||
      '补充记录',
    text,
  })),
}));
export const javaTopics = [
  { id: 'core', name: 'Java 核心', description: '语言特性、泛型、集合、Stream、反射与 I/O' },
  { id: 'concurrency', name: '并发编程', description: 'JMM、锁、并发容器、线程池与虚拟线程' },
  { id: 'jvm', name: 'JVM', description: '类加载、内存、GC、诊断与调优' },
  { id: 'spring', name: 'Spring 与 Web', description: 'Spring、Boot、MVC、事务与接口开发' },
  { id: 'database', name: '数据库与持久化', description: 'SQL、索引、事务、MyBatis/JPA 与连接池' },
  { id: 'middleware', name: '缓存与中间件', description: 'Redis、消息队列、搜索与检索组件' },
  { id: 'cs-basics', name: '计算机基础', description: '网络、操作系统、数据结构与算法' },
  { id: 'architecture', name: '架构与分布式', description: '设计原则、系统设计、可靠性与项目架构' },
  { id: 'engineering', name: '工程化与安全', description: '构建、测试、认证授权与安全防护' },
  { id: 'ops', name: '部署与排障', description: 'Linux、容器、可观测性与故障处理' },
];
export const REVIEW_TAGS = ['重点', '易混淆'];
export const PENDING_TAG = '待整理';
export const PENDING_LIMIT = 10;
export const PENDING_STALE_DAYS = 14;
function firstEventHeadline(markdown: string): string {
  const headings = [...markdown.matchAll(/^(#{1,6})\s+(.+?)\s*$/gm)];
  for (const sectionName of ['今日重大事件', '人工智能产业动态']) {
    const sectionIndex = headings.findIndex((heading) => heading[2].includes(sectionName));
    if (sectionIndex < 0) continue;
    const sectionLevel = headings[sectionIndex][1].length;
    const event = headings[sectionIndex + 1];
    if (event && event[1].length > sectionLevel) {
      return event[2].replace(/^\d+[.、．]\s*/, '').replace(/\*\*|__/g, '').trim();
    }
  }
  return markdown.match(/^#\s+(.+)$/m)?.[1].trim() || '科技情报日报';
}

export const issues: DailyIssue[] = Object.entries(dailyMarkdown)
  .map(([date, markdown]) => ({
    date,
    title: markdown.match(/^#\s+(.+)$/m)?.[1].trim() || '科技情报日报',
    headline: firstEventHeadline(markdown),
    summary: '从重大事件到产业动态、开发者关注与数据指标，八个栏目记录一天的科技与商业变化。',
    articleIds: [],
    supplied: true,
  }))
  .sort((a, b) => b.date.localeCompare(a.date));
export const HOME_LIMIT = 2;
export const BLOG_PAGE_SIZE = 4;
export function articleUrl(article: Pick<Article, 'id'>) {
  return `/articles/${article.id}`;
}
